Repository Z-P0P/ZPOP, pull requests merged in 2022-12, with the labels that each got.

#2 feat: dao + entity
  src/main/java/com/zpop/web/dao/AgeRangeDao.java
  src/main/java/com/zpop/web/dao/CategoryDao.java
  src/main/java/com/zpop/web/dao/CommentDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/MemberDao.java
  src/main/java/com/zpop/web/dao/MemberEvalDao.java
  src/main/java/com/zpop/web/dao/NicknameLogDao.java
  src/main/java/com/zpop/web/dao/NotificationDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dao/RegionDao.java
  src/main/java/com/zpop/web/dao/SocialTypeDao.java
  src/main/java/com/zpop/web/entity/AgeRange.java
  src/main/java/com/zpop/web/entity/Category.java
  src/main/java/com/zpop/web/entity/Comment.java
  src/main/java/com/zpop/web/entity/CommentReportType.java
  src/main/java/com/zpop/web/entity/Meeting.java
  src/main/java/com/zpop/web/entity/MeetingReportType.java
  src/main/java/com/zpop/web/entity/Member.java
  src/main/java/com/zpop/web/entity/MemberEval.java
  src/main/java/com/zpop/web/entity/MemberReportType.java
  src/main/java/com/zpop/web/entity/NicknameLog.java
  src/main/java/com/zpop/web/entity/Notification.java
  src/main/java/com/zpop/web/entity/Participation.java
  src/main/java/com/zpop/web/entity/Region.java
  src/main/java/com/zpop/web/entity/ReportedComment.java
  src/main/java/com/zpop/web/entity/ReportedMeeting.java
  src/main/java/com/zpop/web/entity/ReportedMember.java
  src/main/java/com/zpop/web/entity/SocialType.java
  src/main/resources/application.properties
  src/main/resources/mapper/AgeRangeDaoMapper.xml
  src/main/resources/mapper/CategoryDaoMapper.xml
  src/main/resources/mapper/CommentDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/mapper/RegionDaoMapper.xml
  src/test/java/com/zpop/web/dao/AgeRangeDaoTest.java
  src/test/java/com/zpop/web/dao/CategoryDaoTest.java
  src/test/java/com/zpop/web/dao/Comment.java
  src/test/java/com/zpop/web/dao/CommentDaoTest.java
  src/test/java/com/zpop/web/dao/MeetingDaoTest.java
  src/test/java/com/zpop/web/dao/ParticipationDaoTest.java
  src/test/java/com/zpop/web/dao/RegionDaoTest.java
Labels: feat

#4 Feat: dao, mapper 및 이름 개선
  src/main/java/com/zpop/web/dao/CommentDao.java
  src/main/java/com/zpop/web/dao/CommentReportTypeDao.java
  src/main/java/com/zpop/web/dao/MeetingReportTypeDao.java
  src/main/java/com/zpop/web/dao/MemberReportTypeDao.java
  src/main/java/com/zpop/web/dao/ReportedCommentDao.java
  src/main/java/com/zpop/web/dao/ReportedMeetingDao.java
  src/main/java/com/zpop/web/dao/ReportedMemberDao.java
  src/main/java/com/zpop/web/entity/CommentReportType.java
  src/main/java/com/zpop/web/entity/MeetingReportType.java
  src/main/java/com/zpop/web/entity/MemberReportType.java
  src/main/java/com/zpop/web/entity/ReportedComment.java
  src/main/java/com/zpop/web/entity/ReportedMeeting.java
  src/main/java/com/zpop/web/entity/ReportedMember.java
  src/main/resources/application.properties
  src/main/resources/mapper/CommentDaoMapper.xml
  src/main/resources/mapper/CommentReportTypeDaoMapper.xml
  src/main/resources/mapper/MeetingReportTypeDaoMapper.xml
  src/main/resources/mapper/MemberReportTypeDaoMapper.xml
  src/main/resources/mapper/NotificationDaoMapper.xml
  src/main/resources/mapper/ReportedCommentDaoMapper.xml
  src/main/resources/mapper/ReportedMeetingDaoMapper.xml
  src/main/resources/mapper/ReportedMemberDaoMapper.xml
  src/test/java/com/zpop/web/dao/Comment.java
  src/test/java/com/zpop/web/dao/CommentDaoTest.java
Labels: feat, refactoring

#10 feat: 카카오/네이버 소셜 로그인 기능 추가
  .gitignore
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/java/com/zpop/web/controller/LogoutController.java
  src/main/java/com/zpop/web/service/KakaoLoginService.java
  src/main/java/com/zpop/web/service/LoginService.java
  src/main/java/com/zpop/web/service/NaverLoginService.java
  src/main/java/com/zpop/web/service/TokenResponse.java
  src/main/resources/application.properties
  src/main/resources/static/css/button.css
  src/main/resources/static/js/member/login.js
Labels: feat, question

#7 Feat: get meetings
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dto/MeetingThumbnailPagination.java
  src/main/java/com/zpop/web/dto/MeetingThumbnailResponse.java
  src/main/java/com/zpop/web/entity/meeting/Meeting.java
  src/main/java/com/zpop/web/entity/meeting/MeetingThumbnailView.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/static/css/deco.css
  src/main/resources/static/css/form.css
  src/main/resources/static/css/icon.css
  src/main/resources/static/css/loading.css
  src/main/resources/static/css/member/component/header.css
  src/main/resources/static/css/member/component/meeting-category.css
  src/main/resources/static/css/member/component/meeting.css
  src/main/resources/static/css/member/component/search-bar.css
  src/main/resources/static/css/member/component/select.css
  src/main/resources/static/css/member/meeting/list.css
  src/main/resources/static/css/member/style.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/images/icon/speech-bubble.svg
  src/main/resources/static/js/meeting/list.js
  src/main/resources/static/js/member/select.js
  src/main/resources/templates/meeting/list.html
  src/test/java/com/zpop/web/dao/MeetingDaoTest.java
Labels: feat

#17 feat: 로그인/비로그인 사용자 헤더 적용 및 layout 반영
  pom.xml
  src/main/resources/static/css/member/component/header.css
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/inc/layout.html
Labels: feat

#19 feat: delete meeting
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/application.properties
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/form-fixed.css
  src/main/resources/static/css/form.css
  src/main/resources/static/css/icon.css
  src/main/resources/static/css/member/component/header.css
  src/main/resources/static/js/meeting/list.js
  src/main/resources/templates/inc/layout.html
  src/main/resources/templates/meeting/list.html
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: chore, feat

#21 cleanup: add-comment branch
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/LogoutController.java
  src/main/resources/templates/comment/comment.html
Labels: cleanup

#23 Feat: 모임 리스트 조회 화면, 기능 개선
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/dto/MeetingThumbnailResponse.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/utils/TextDateTimeCalculator.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/static/css/button.css
  src/main/resources/static/css/deco.css
  src/main/resources/static/css/member/component/header.css
  src/main/resources/static/css/member/component/meeting-category.css
  src/main/resources/static/css/member/component/meeting.css
  src/main/resources/static/css/member/component/region-bar.css
  src/main/resources/static/css/member/component/search-bar.css
  src/main/resources/static/css/member/component/select.css
  src/main/resources/static/css/member/meeting/list.css
  src/main/resources/static/images/banner.png
  src/main/resources/static/js/meeting/category.js
  src/main/resources/static/js/meeting/list.js
  src/main/resources/static/js/meeting/region.js
  src/main/resources/templates/admin/banner/list.html
  src/main/resources/templates/admin/comment/list.html
  src/main/resources/templates/admin/meeting/category.html
  src/main/resources/templates/admin/meeting/list.html
  src/main/resources/templates/admin/meeting/region.html
  src/main/resources/templates/admin/report/list.html
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/meeting/list.html
Labels: feat, refactoring

#25 refactor: 모임 상세보기의 케밥 모달 임시 구현
  src/main/java/com/zpop/web/controller/HomeController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/resources/static/css/member/component/meeting-info.css
  src/main/resources/templates/inc/select-modal.html
  src/main/resources/templates/meeting/detail-imple.html
Labels: feat, refactoring

#31 Feat: get meetings
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/dto/MeetingThumbnailPagination.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/static/css/loading.css
  src/main/resources/static/css/member/meeting/list.css
  src/main/resources/static/js/meeting/category.js
  src/main/resources/static/js/meeting/list.js
  src/main/resources/static/js/meeting/list/list.js
  src/main/resources/static/js/meeting/list/on-click-category.js
  src/main/resources/static/js/meeting/list/on-click-region.js
  src/main/resources/static/js/meeting/list/on-click-toggle.js
  src/main/resources/static/js/meeting/list/on-scroll.js
  src/main/resources/static/js/meeting/list/on-search.js
  src/main/resources/static/js/meeting/list/request-meetings.js
  src/main/resources/static/js/meeting/list/state.js
  src/main/resources/static/js/meeting/list/util.js
  src/main/resources/static/js/meeting/list/view.js
  src/main/resources/static/js/meeting/region.js
  src/main/resources/templates/meeting/list.html
Labels: feat, refactoring

#38 Feature/admin meeting (관리자 모임관리 기능)
  src/main/java/com/zpop/web/controller/admin/MeetingController.java
  src/main/java/com/zpop/web/controller/admin/MemberController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/MemberDao.java
  src/main/java/com/zpop/web/dto/admin/AdminMeetingDto.java
  src/main/java/com/zpop/web/entity/meeting/AdminMeetingView.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/java/com/zpop/web/service/admin/AdminMeetingService.java
  src/main/java/com/zpop/web/service/admin/DefaultAdminMeetingService.java
  src/main/resources/application.properties
  src/main/resources/mapper/AdminMeetingDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/MemberDaoMapper.xml
  src/main/resources/static/css/admin/component/admin-list.css
  src/main/resources/static/css/admin/component/admin-nav.css
  src/main/resources/static/css/admin/component/admin-search-bar.css
  src/main/resources/static/css/admin/component/header.css
  src/main/resources/static/css/admin/component/status.css
  src/main/resources/static/css/admin/component/table-bar.css
  src/main/resources/static/css/admin/style.css
  src/main/resources/static/css/deco.css
  src/main/resources/static/images/icon/up-down.svg
  src/main/resources/static/images/icon/user-ban.svg
  src/main/resources/static/images/icon/user-check.svg
  src/main/resources/static/images/icon/user-suspend.svg
  src/main/resources/templates/admin/meeting/list.html
  src/main/resources/templates/admin/member/list.html
  src/main/resources/templates/meeting/list.html
Labels: feat

#37 Feature/admin report (관리자의 신고 관리 기능)
  src/main/java/com/zpop/web/controller/admin/ReportController.java
  src/main/java/com/zpop/web/dao/ReportedCommentDao.java
  src/main/java/com/zpop/web/dao/ReportedMeetingDao.java
  src/main/java/com/zpop/web/dao/ReportedMemberDao.java
  src/main/java/com/zpop/web/dto/admin/AdminReportedCommentDto.java
  src/main/java/com/zpop/web/dto/admin/AdminReportedMeetingDto.java
  src/main/java/com/zpop/web/dto/admin/AdminReportedMemberDto.java
  src/main/java/com/zpop/web/service/admin/AdminReportService.java
  src/main/java/com/zpop/web/service/admin/DefaultAdminReportService.java
  src/main/resources/mapper/ReportedCommentDaoMapper.xml
  src/main/resources/mapper/ReportedMeetingDaoMapper.xml
  src/main/resources/mapper/ReportedMemberDaoMapper.xml
  src/main/resources/templates/admin/report/comment.html
  src/main/resources/templates/admin/report/list.html
  src/main/resources/templates/admin/report/meeting.html
  src/main/resources/templates/admin/report/member.html
Labels: feat

#44 Feature/모임 등록, 모임 상세조회, 모임 참여하기
  pom.xml
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/CategoryDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/MeetingDetailDto.java
  src/main/java/com/zpop/web/dto/MeetingParticipantsDto.java
  src/main/java/com/zpop/web/dto/MeetingRegisterDto.java
  src/main/java/com/zpop/web/entity/Participation.java
  src/main/java/com/zpop/web/entity/meeting/Meeting.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/mapper/CategoryDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/member/component/modal-2.css
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/static/js/meeting/register.js
  src/main/resources/static/js/member/select.js
  src/main/resources/static/js/utils/quill-generator.js
  src/main/resources/templates/inc/meeting-detail-modal.html
  src/main/resources/templates/meeting/detail.html
  src/main/resources/templates/meeting/register.html
  src/main/resources/templates/meeting/test.html
Labels: feat

#43 #42 fixed: related to meeting "isClosed" column by change
  src/main/java/com/zpop/web/dto/MyMeetingResponse.java
  src/main/java/com/zpop/web/entity/member/MyMeetingView.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
Labels: fix

#45 Fix/meeting test
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/test/java/com/zpop/web/dao/MeetingDaoTest.java
Labels: fix

#46 fix/restore participate
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dto/MeetingRegisterDto.java
  src/main/java/com/zpop/web/entity/meeting/Meeting.java
Labels: fix

#50 fix: add reply
  src/main/resources/static/js/comment/comment.js
  src/main/resources/static/js/comment/reply.js
  src/main/resources/templates/meeting/detail2.html
Labels: fix

#49 feat: 404 page
  src/main/java/com/zpop/web/global/exception/ExceptionHandlerControllerAdvice.java
  src/main/resources/static/css/404.css
  src/main/resources/templates/error/404.html
Labels: feat

#47 feat: close meeting
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/entity/meeting/Meeting.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat, test

#52 feat: admin meeting (모임글 상세보기 모달 및 조회기능 구현)
  pom.xml
  src/main/java/com/zpop/web/controller/admin/MeetingController.java
  src/main/java/com/zpop/web/dao/AgeRangeDao.java
  src/main/java/com/zpop/web/dao/CategoryDao.java
  src/main/java/com/zpop/web/dao/ContactTypeDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/RegionDao.java
  src/main/java/com/zpop/web/dto/AgeRangeDto.java
  src/main/java/com/zpop/web/dto/CategoryDto.java
  src/main/java/com/zpop/web/dto/ContactTypeDto.java
  src/main/java/com/zpop/web/dto/ParticipantDto.java
  src/main/java/com/zpop/web/dto/RegionDto.java
  src/main/java/com/zpop/web/dto/admin/AdminMeetingDetailsDto.java
  src/main/java/com/zpop/web/dto/admin/AdminMeetingDetailsResponse.java
  src/main/java/com/zpop/web/dto/admin/AdminMeetingDto.java
  src/main/java/com/zpop/web/entity/AgeRange.java
  src/main/java/com/zpop/web/entity/Category.java
  src/main/java/com/zpop/web/entity/ContactType.java
  src/main/java/com/zpop/web/entity/Region.java
  src/main/java/com/zpop/web/service/admin/AdminMeetingService.java
  src/main/java/com/zpop/web/service/admin/DefaultAdminMeetingService.java
  src/main/resources/mapper/AgeRangeDaoMapper.xml
  src/main/resources/mapper/CategoryDaoMapper.xml
  src/main/resources/mapper/ContactTypeDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/mapper/RegionDaoMapper.xml
  src/main/resources/static/css/admin/component/button.css
  src/main/resources/static/css/admin/component/modal.css
  src/main/resources/static/css/admin/component/select.css
  src/main/resources/static/css/admin/component/table-bar.css
  src/main/resources/static/js/admin/meeting.js
  src/main/resources/static/js/admin/select.js
  src/main/resources/templates/admin/meeting/list.html
Labels: feat

#53 feat: kick participant
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/entity/Participation.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat, fix, test

#24 feat : 알림 조회, 신고 service 구현
  src/main/java/com/zpop/web/controller/NotificationController.java
  src/main/java/com/zpop/web/controller/ReportedCommentController.java
  src/main/java/com/zpop/web/controller/ReportedMeetingController.java
  src/main/java/com/zpop/web/controller/ReportedMemberController.java
  src/main/java/com/zpop/web/dao/NotificationDao.java
  src/main/java/com/zpop/web/dao/ReportedCommentDao.java
  src/main/java/com/zpop/web/dao/ReportedMeetingDao.java
  src/main/java/com/zpop/web/dao/ReportedMemberDao.java
  src/main/java/com/zpop/web/dto/NotificationDto.java
  src/main/java/com/zpop/web/dto/RequestCommentReportDto.java
  src/main/java/com/zpop/web/dto/RequestMeetingReportDto.java
  src/main/java/com/zpop/web/dto/RequestMemberReportDto.java
  src/main/java/com/zpop/web/entity/Notification.java
  src/main/java/com/zpop/web/entity/ReportedComment.java
  src/main/java/com/zpop/web/entity/ReportedMeeting.java
  src/main/java/com/zpop/web/entity/ReportedMember.java
  src/main/java/com/zpop/web/service/DefaultNotificationService.java
  src/main/java/com/zpop/web/service/DefaultReportService.java
  src/main/java/com/zpop/web/service/NotificationService.java
  src/main/java/com/zpop/web/service/ReportService.java
  src/main/resources/mapper/NotificationDaoMapper.xml
  src/main/resources/mapper/ReportedCommentDaoMapper.xml
  src/main/resources/mapper/ReportedMeetingDaoMapper.xml
  src/main/resources/mapper/ReportedMemberDaoMapper.xml
  src/main/resources/static/css/member/component/notification-modal.css
  src/main/resources/static/css/member/component/report-modal.css
  src/main/resources/templates/notification/notification-modal.html
  src/main/resources/templates/report/comment.html
  src/main/resources/templates/report/meeting.html
  src/main/resources/templates/report/member.html
Labels: feat

#54 feat: 댓글 모임 상세 조회에 병합, 참여하기 구현
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/admin/MeetingController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/java/com/zpop/web/service/admin/AdminMeetingService.java
  src/main/java/com/zpop/web/service/admin/DefaultAdminMeetingService.java
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/member/component/participant.css
  src/main/resources/static/js/comment/comment.js
  src/main/resources/static/js/comment/reply.js
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/templates/meeting/detail.html
  src/test/java/com/zpop/web/dao/ParticipationDaoTest.java
Labels: feat

#56 chore: spring security
  pom.xml
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/java/com/zpop/web/controller/RegisterController.java
  src/main/java/com/zpop/web/security/SecurityConfig.java
  src/main/java/com/zpop/web/security/UserRole.java
  src/main/java/com/zpop/web/security/UserSecurityService.java
  src/main/java/com/zpop/web/security/ZpopUserDetails.java
  src/main/resources/static/js/header.js
  src/main/resources/static/js/member/register.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/inc/layout.html
  src/main/resources/templates/register.html
Labels: chore, feat

#60 fix: 모임 리스트 조회 지역 옵션 버그
  src/main/resources/templates/meeting/detail-imple.html
  src/main/resources/templates/meeting/list.html
Labels: fix

#59 feat: register meeting
  pom.xml
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/CategoryDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/RegisterMeetingRequest.java
  src/main/java/com/zpop/web/dto/RegisterMeetingResponse.java
  src/main/java/com/zpop/web/dto/admin/AdminCategoryDto.java
  src/main/java/com/zpop/web/security/SecurityConfig.java
  src/main/java/com/zpop/web/security/UserRole.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/member/component/select.css
  src/main/resources/static/css/member/meeting/create.css
  src/main/resources/static/css/member/meeting/list.css
  src/main/resources/static/js/admin/select.js
  src/main/resources/static/js/meeting/register.js
  src/main/resources/static/js/member/select.js
  src/main/resources/templates/meeting/detail.html
  src/main/resources/templates/meeting/list.html
  src/main/resources/templates/meeting/register.html
Labels: feat

#62 feat: cancel participation
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat, test

#63 Feature/notification
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/NotificationDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/service/CommentService.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/DefaultNotificationService.java
  src/main/java/com/zpop/web/service/KakaoLoginService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/NotificationDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
Labels: feat

#61 fix: security
  src/main/java/com/zpop/web/security/SecurityConfig.java
Labels: fix
