Repository Z-P0P/ZPOP, pull requests merged in 2023-02, with the labels that each got.

#247 [feat] 반응형 동적 댓글 버튼 구현
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentBox.vue
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/comment/CommentModal.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/Reply.vue
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/stores/commentStore.js
  src/main/vue/src/stores/replyStore.js
Labels: feat

#244 feat: 회원 프로필 수정
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/vue/src/assets/css/member/mypage.css
  src/main/vue/src/components/member/ProfileEdit.vue
Labels: feat, help wanted

#246 cleanup: 마이 페이지 코드 클린업 , 모달 오류
  src/main/vue/src/assets/css/member/rate.css
  src/main/vue/src/components/member/ProfileEdit.vue
  src/main/vue/src/components/modal/Changed.vue
  src/main/vue/src/views/member/Edit.vue
  src/main/vue/src/views/member/MyMeeting.vue
  src/main/vue/src/views/member/Profile.vue
Labels: cleanup, fix, v2

#249 fix: 닉네임 설정 화면에서 닉네임이 공란일 때 로그인 설정버튼을 누르면 넘어가는 버그 수정
  src/main/vue/src/components/modal/NicknameRegister.vue
Labels: fix

#251 Fix/bug
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/vue/src/components/member/ProfileEdit.vue
Labels: fix

#252 Newlecture 로고 추가
  src/main/webapp/image/KakaoTalk_Photo_2023-02-01-17-40-07.jpeg
  src/main/webapp/image/meeting/ZPOP_MEETING_2023_02_01_17_40_17_749.jpeg
Labels: chore

#253 fix: 내 프로필에 내 사진 반영
  src/main/vue/src/assets/css/member/mypage.css
  src/main/vue/src/components/member/MyProfile.vue
  src/main/webapp/image/profile/ZPOP_PROFILE_2023_02_01_17_40_28_612.jpg
  src/main/webapp/image/profile/ZPOP_PROFILE_2023_02_01_17_47_58_287.jpg
  src/main/webapp/image/profile/ZPOP_PROFILE_2023_02_01_18_12_05_612.png
Labels: fix

#257 fix: 닉네임 입력 없이 프로필 수정 되던 현상 수정
  src/main/java/com/zpop/web/service/DefalutMemberService.java
Labels: fix

#259 feat: 동적 프로필 수정 저장하기 버튼 구현
  src/main/vue/src/components/member/ProfileEdit.vue
Labels: feat

#260 [Fix] 댓글 수정시 오류
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/webapp/image/profile/ZPOP_PROFILE_2023_02_01_20_51_14_867.jpg
Labels: fix

#264 refactor: 모임 등록후 이동 수정
  src/main/vue/src/views/meeting/Register.vue
Labels: refactoring

#265 Feature/notification route modified
  src/main/java/com/zpop/web/controller/LoginController.java
Labels: feat, fix

#269 fix: resolve evaluation bugs
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/vue/src/components/header/NotificationModal.vue
Labels: bug
