Repository Z-P0P/ZPOP, pull requests merged in 2023-01, with the labels that each got.

#66 feat: 모임 참여자 강퇴하기에 탈퇴 회원 예외처리
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/entity/Member.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat, fix

#65 Feature/edit comment
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dao/CommentDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/MeetingDetailDto.java
  src/main/java/com/zpop/web/dto/MeetingParticipantsDto.java
  src/main/java/com/zpop/web/entity/comment/CommentView.java
  src/main/java/com/zpop/web/service/CommentService.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/mapper/CommentDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/member/component/comment.css
  src/main/resources/static/css/member/meeting/detail.css
  src/main/resources/static/js/comment/comment.js
  src/main/resources/static/js/comment/reply.js
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/templates/inc/meeting-detail-modal.html
  src/main/resources/templates/meeting/detail.html
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat

#69 Feature/edit comment
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/ReplyController.java
  src/main/java/com/zpop/web/dao/CommentDao.java
  src/main/java/com/zpop/web/entity/ReportedComment.java
  src/main/java/com/zpop/web/entity/comment/CommentView.java
  src/main/java/com/zpop/web/service/CommentService.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/java/com/zpop/web/service/DefaultReportService.java
  src/main/resources/mapper/CommentDaoMapper.xml
  src/main/resources/static/js/comment/comment.js
  src/main/resources/static/js/comment/edit-comment.js
  src/main/resources/static/js/comment/reply.js
  src/main/resources/templates/inc/meeting-detail-modal.html
  src/main/resources/templates/meeting/detail.html
Labels: feat, fix

#70 Feature/notification
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/java/com/zpop/web/controller/ReportedCommentController.java
  src/main/java/com/zpop/web/controller/ReportedMeetingController.java
  src/main/java/com/zpop/web/controller/ReportedMemberController.java
  src/main/java/com/zpop/web/dao/ReportedCommentDao.java
  src/main/java/com/zpop/web/service/DefaultReportService.java
  src/main/java/com/zpop/web/service/KakaoLoginService.java
  src/main/java/com/zpop/web/service/ReportService.java
  src/main/resources/mapper/ReportedCommentDaoMapper.xml
  src/main/resources/static/js/member/notification.js
  src/main/resources/static/js/member/select-report.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/inc/layout.html
  src/main/resources/templates/report/comment.html
  src/main/resources/templates/report/meeting.html
  src/main/resources/templates/report/member.html
Labels: feat

#68 refactor: 모임 리스트 조회 - 모임 시작 시간과 관련한 로직 수정
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
Labels: cleanup, refactoring

#73 fix: 헤더 href
  src/main/resources/static/js/header.js
  src/main/resources/templates/comment/comment.html
  src/main/resources/templates/comment/reply.html
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/meeting/detail2.html
Labels: cleanup, fix

#74 fix: 모임 조회 페이지 조회 결과 없을 때 버그 수정
  src/main/resources/static/js/meeting/list/on-click-category.js
  src/main/resources/static/js/meeting/list/on-click-region.js
  src/main/resources/static/js/meeting/list/on-click-toggle.js
Labels: fix

#76 feat: get meeting contact
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
Labels: feat

#78 Feat/popup
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/resources/static/css/popup.css
  src/main/resources/static/images/banner-mobile.png
  src/main/resources/static/images/banner-pc.png
  src/main/resources/static/js/member/profile-edit.js
  src/main/resources/templates/meeting/list.html
  src/main/resources/templates/member/my-profile.html
  src/main/resources/templates/member/profile-edit.html
  src/main/resources/templates/popup.html
Labels: feat

#79 Feature/edit comment
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/ReplyController.java
  src/main/java/com/zpop/web/service/CommentService.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/resources/mapper/CommentDaoMapper.xml
  src/main/resources/mapper/ReportedCommentDaoMapper.xml
  src/main/resources/static/css/button.css
  src/main/resources/static/css/member/component/comment.css
  src/main/resources/static/css/member/component/reply.css
  src/main/resources/static/js/comment/comment.js
  src/main/resources/static/js/comment/edit-comment.js
  src/main/resources/static/js/comment/edit-reply.js
  src/main/resources/static/js/comment/reply.js
  src/main/resources/static/js/member/login.js
  src/main/resources/templates/meeting/detail.html
Labels: refactoring

#77 refactor: 모임 상세조회 개선
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dao/CategoryDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/CommentResponse.java
  src/main/java/com/zpop/web/dto/MeetingDetailResponse.java
  src/main/java/com/zpop/web/dto/ParticipantResponse.java
  src/main/java/com/zpop/web/entity/participation/ParticipationInfoView.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/CategoryDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/button.css
  src/main/resources/static/js/comment/reply.js
  src/main/resources/templates/meeting/detail.html
Labels: refactoring

#81 Feature/notification
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/ReportedCommentController.java
  src/main/resources/static/css/member/component/notification-modal.css
  src/main/resources/static/js/meeting/report.js
  src/main/resources/static/js/member/notification.js
  src/main/resources/templates/inc/meeting-detail-modal.html
  src/main/resources/templates/meeting/detail.html
Labels: feat, fix

#83 fix: 헤더 셀렉트 모달 수정
  src/main/resources/static/css/member/component/header.css
  src/main/resources/static/css/member/component/select.css
  src/main/resources/static/js/meeting/list/list.js
  src/main/resources/templates/inc/header.html
Labels: fix

#85 refactor: 모임 참여하기 개선
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/templates/meeting/detail.html
Labels: refactoring

#87 Feat/my page: when user click rate button, showing participants list
  pom.xml
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/MemberDao.java
  src/main/java/com/zpop/web/dto/EvalMemberDto.java
  src/main/java/com/zpop/web/entity/meeting/AdminMeetingView.java
  src/main/java/com/zpop/web/entity/meeting/Meeting.java
  src/main/java/com/zpop/web/entity/member/MyMeetingView.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/mapper/MemberDaoMapper.xml
  src/main/resources/static/css/member/meeting/profile-modal.css
  src/main/resources/static/css/member/member/rate.css
  src/main/resources/static/css/member/popup.css
  src/main/resources/static/css/popup.css
  src/main/resources/static/js/meeting/profile-modal.js
  src/main/resources/static/js/member/my-meeting.js
  src/main/resources/static/js/member/popup.js
  src/main/resources/templates/meeting/list.html
  src/main/resources/templates/member/my-gathering.html
  src/main/resources/templates/member/my-meeting.html
  src/main/resources/templates/member/profile-edit.html
  src/main/resources/templates/member/rate.html
  src/main/resources/templates/popup.html
Labels: feat, fix

#88 feat : 403 whitelabel 대신 로그인 alert로 수정
  src/main/java/com/zpop/web/security/SecurityConfig.java
  src/main/java/com/zpop/web/security/ZpopAuthenticationEntryPoint.java
Labels: feat

#89 fix : notification logout bug fixed
  src/main/resources/static/js/member/notification.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/inc/layout.html
Labels: feat, fix

#90 Feature/report
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/ReportController.java
  src/main/java/com/zpop/web/controller/ReportedCommentController.java
  src/main/java/com/zpop/web/dto/RequestCommentReportDto.java
  src/main/resources/static/js/comment/edit-comment.js
  src/main/resources/static/js/meeting/report.js
  src/main/resources/templates/meeting/detail.html
Labels: feat

#91 feat: increase comment count
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
Labels: feat

#92 Feature/meeting ajax
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dto/CommentResponse.java
  src/main/java/com/zpop/web/dto/MeetingDetailResponse.java
  src/main/java/com/zpop/web/dto/MeetingParticipantsDto.java
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/static/css/member/.DS_Store
  src/main/resources/static/css/member/popup.css
  src/main/resources/static/js/comment/edit-comment.js
  src/main/resources/static/js/comment/edit-reply.js
  src/main/resources/static/js/meeting/report.js
  src/main/resources/templates/inc/layout.html
  src/main/resources/templates/meeting/detail.html
  src/test/java/com/zpop/web/dao/CategoryDaoTest.java
Labels: refactoring

#93 feat: 닉네임 설정 모달 개선 및 CSS 적용
  src/main/java/com/zpop/web/controller/RegisterController.java
  src/main/java/com/zpop/web/service/RegisterService.java
  src/main/resources/static/css/form.css
  src/main/resources/static/css/member/component/modal.css
  src/main/resources/static/css/member/style.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/images/logo/logo-only-text.svg
  src/main/resources/static/js/member/register.js
  src/main/resources/templates/inc/layout.html
  src/main/resources/templates/register.html
Labels: feat

#96 refactor: 모임 참여자 목록 얻기 개선
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
Labels: refactoring

#97 Fix : notification modal css class names changed
  src/main/resources/static/css/member/component/notification-modal.css
Labels: feat

#98 Cleanup/log
  src/main/java/com/zpop/web/security/ZpopAuthenticationEntryPoint.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/NaverLoginService.java
  src/main/java/com/zpop/web/service/RegisterService.java
  src/main/resources/static/js/admin/meeting.js
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/static/js/meeting/register.js
  src/main/resources/static/js/meeting/report-select.js
  src/main/resources/static/js/meeting/report.js
  src/main/resources/static/js/meeting/update.js
  src/main/resources/static/js/member/calendar.js
  src/main/resources/static/js/member/my-meeting.js
  src/main/resources/static/js/member/notification.js
  src/main/resources/static/js/member/select-report.js
  src/main/resources/templates/meeting/test.html
  src/main/resources/templates/notification/notification-modal.html
  src/test/java/com/zpop/web/dao/AgeRangeDaoTest.java
  src/test/java/com/zpop/web/dao/RegionDaoTest.java
Labels: cleanup

#100 fix: 모임 상세조회 모달 겹쳐지는 문제
  src/main/resources/static/css/deco.css
  src/main/resources/templates/inc/meeting-detail-modal.html
  src/main/resources/templates/meeting/detail.html
Labels: fix

#99 feat : report complete modal added
  src/main/java/com/zpop/web/controller/ReportedCommentController.java
  src/main/java/com/zpop/web/controller/ReportedMeetingController.java
  src/main/java/com/zpop/web/controller/ReportedMemberController.java
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/member/component/report-modal.css
  src/main/resources/static/js/meeting/report.js
  src/main/resources/templates/meeting/detail.html
  src/main/resources/templates/report/report-complete.css
  src/main/resources/templates/report/report-complete.html
Labels: feat, fix

#102 fix: 댓글 수정, 삭제에 시큐리티 반영 및 로직 예외 추가
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/service/CommentService.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
Labels: fix, refactoring

#103 feat: 댓글 삭제시 모임 댓글 수 감소
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/resources/mapper/MeetingDaoMapper.xml
Labels: feat

#104 Feature : Rate Member's fame
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/MemberDao.java
  src/main/java/com/zpop/web/dao/MemberEvalDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/EvalDto.java
  src/main/java/com/zpop/web/entity/MemberEval.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/mapper/MeetingFileDaoMapper.xml
  src/main/resources/mapper/MemberDaoMapper.xml
  src/main/resources/mapper/MemberEvalDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/member/member/rate.css
  src/main/resources/static/css/member/member/slider.css
  src/main/resources/static/js/member/my-meeting.js
  src/main/resources/templates/member/my-meeting.html
Labels: feat, fix, help wanted

#105 Feature/meeting ajax
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/entity/participation/ParticipationInfoView.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/resources/static/css/button.css
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/static/js/meeting/manage.js
  src/main/resources/templates/meeting/detail.html
Labels: feat

#108 refactor: block anonymous access to buttons of detail page
  src/main/java/com/zpop/web/controller/ReplyController.java
  src/main/resources/static/js/comment/comment.js
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/templates/meeting/detail.html
Labels: refactoring

#111 [MINOR BUG FIX] 배너 우측버튼 클릭 시 계속해서 넘어가는 현상 수정
  src/main/resources/static/css/member/meeting/list.css
  src/main/resources/static/js/meeting/list/banner.js
Labels: fix

#109 Feature: profile modal & Fix: misspelling & Cleanup codes
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/controller/ReplyController.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/static/css/icon.css
  src/main/resources/static/css/member/member/profile-modal.css
  src/main/resources/static/images/icon/door.svg
  src/main/resources/static/images/icon/hamburger.svg
  src/main/resources/static/images/icon/siren-white-btn.svg
  src/main/resources/static/images/minji.jpg
  src/main/resources/static/js/member/my-meeting.js
  src/main/resources/static/js/member/profile-edit.js
  src/main/resources/static/js/member/profile-modal.js
  src/main/resources/static/js/member/rate-modal.js
  src/main/resources/templates/meeting/detail.html
  src/main/resources/templates/member/my-gathering.html
  src/main/resources/templates/member/my-meeting.html
  src/main/resources/templates/member/profile-edit.html
  src/main/resources/templates/member/rate.html
Labels: cleanup, feat, fix

#113 [FEAT] 참여링크 표시 기능 추가 (& 모달 추가) 및 모임글 작성 시 제목에 붉은색 focus 되는 현상 수정
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/mapper/MeetingFileDaoMapper.xml
  src/main/resources/static/css/member/component/modal-2.css
  src/main/resources/static/js/meeting/detail.js
  src/main/resources/templates/meeting/detail.html
  src/main/resources/templates/meeting/register.html
  src/main/resources/templates/register.html
Labels: feat, fix

#114 fix: remove localhost:8080 from fetch URLs
  src/main/resources/static/js/member/notification.js
  src/main/resources/templates/meeting/test.html
Labels: fix

#118 feat: 모임 상세조회 (모임 정보 api)
  .gitignore
  backend/src/main/java/com/zpop/web/ageRange/enums/AgeRangeType.java
  backend/src/main/java/com/zpop/web/category/enums/CategoryType.java
  backend/src/main/java/com/zpop/web/controller/MeetingController.java
  backend/src/main/java/com/zpop/web/controller/TempMeetingController.java
  backend/src/main/java/com/zpop/web/global/config/WebConfig.java
  backend/src/main/java/com/zpop/web/meeting/controller/MeetingController.java
  backend/src/main/java/com/zpop/web/meeting/dto/MeetingResponse.java
  backend/src/main/java/com/zpop/web/meeting/entity/Meeting.java
  backend/src/main/java/com/zpop/web/meeting/enums/Gender.java
  backend/src/main/java/com/zpop/web/meeting/repository/MeetingRepository.java
  backend/src/main/java/com/zpop/web/meeting/service/MeetingService.java
  backend/src/main/java/com/zpop/web/member/repository/MemberRepository.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/api/index.js
  frontend/src/api/meeting.js
  frontend/src/assets/css/deco.css
  frontend/src/assets/logo.png
  frontend/src/components/HelloWorld.vue
  frontend/src/components/meeting/Article.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/views/meeting/Detail.vue
Labels: feat, v2

#120 feat: 기본 모달 & 검색
  src/main/vue/src/App.vue
  src/main/vue/src/assets/css/meeting/thumbnail-list.css
  src/main/vue/src/components/header/header.vue
  src/main/vue/src/components/header/login-modal.vue
  src/main/vue/src/components/modal/Default.vue
  src/main/vue/src/router/index.js
  src/main/vue/src/views/Layout.vue
  src/main/vue/src/views/meeting/List.vue
  src/main/vue/src/views/meeting/Search.vue
Labels: feat

#121 feat: 서버 에러 모달 구현
  src/main/vue/src/components/modal/ServerError.vue
  src/main/vue/src/utils/ServerException.js
  src/main/vue/src/views/Layout.vue
  src/main/vue/src/views/meeting/List.vue
  src/main/vue/src/views/meeting/Search.vue
Labels: feat

#125 fix: 기존 탭에서 로그인한 상태에서 새 탭으로 접속 시 로그인 정보가 유지되지 않는 문제 해결
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/vue/src/stores/memberStore.js
Labels: fix

#126 [FEAT,FIX] 게시글 작성 기능 & 모달 버그 수정 (이벤트 버블링)
  .gitignore
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/vue/index.html
  src/main/vue/src/api/meeting.js
  src/main/vue/src/assets/css/component/select.css
  src/main/vue/src/assets/css/deco.css
  src/main/vue/src/assets/css/form.css
  src/main/vue/src/components/header/Profile.vue
  src/main/vue/src/components/meeting/MeetingFormDateInput.vue
  src/main/vue/src/components/meeting/MeetingFormSelectInput.vue
  src/main/vue/src/components/meeting/MeetingFormSelectTextInput.vue
  src/main/vue/src/components/meeting/MeetingFormTextInput.vue
  src/main/vue/src/components/meeting/SelectBox.vue
  src/main/vue/src/components/modal/Default.vue
  src/main/vue/src/utils/quill-generator.js
  src/main/vue/src/utils/register.js
  src/main/vue/src/views/meeting/Register.vue
Labels: feat, fix

#128 feat: 404 views
  src/main/vue/src/router/index.js
  src/main/vue/src/views/404.vue
Labels: feat

#129 feat: 모임 리스트 조회 토글 옵션
  src/main/vue/src/assets/css/meeting/thumbnail-list.css
  src/main/vue/src/components/button/SoftToggle.vue
  src/main/vue/src/components/button/Toggle.vue
  src/main/vue/src/components/meeting/option-control/OptionControl.vue
  src/main/vue/src/stores/meetingListStore.js
Labels: feat

#132 Feature: my profile, my profile-edit , rate modal, my meeting
  README.md
  src/main/vue/src/api/member.js
  src/main/vue/src/assets/css/member/meeting-list.css
  src/main/vue/src/assets/css/member/mypage.css
  src/main/vue/src/assets/css/member/rate.css
  src/main/vue/src/components/member/MeetingList.vue
  src/main/vue/src/components/member/MyProfile.vue
  src/main/vue/src/components/member/ProfileEdit.vue
  src/main/vue/src/components/modal/Full.vue
  src/main/vue/src/router/index.js
  src/main/vue/src/views/member/Edit.vue
  src/main/vue/src/views/member/MyGathering.vue
  src/main/vue/src/views/member/MyMeeting.vue
  src/main/vue/src/views/member/Profile.vue
Labels: bug, feat, v2

#134 fixed: apply vue css (detail page - article, comment, participant, etc.)
  src/main/vue/src/assets/css/meeting/article.css
  src/main/vue/src/assets/css/meeting/component/comment.css
  src/main/vue/src/assets/css/meeting/component/participant.css
  src/main/vue/src/assets/css/meeting/component/profile-box.css
  src/main/vue/src/assets/css/meeting/detail.css
  src/main/vue/src/components/meeting/Participants.vue
  src/main/vue/src/components/meeting/Thumbnail.vue
  src/main/vue/src/views/meeting/Detail.vue
Labels: bug, fix, help wanted

#135 [FEAT] 메인의 모임글 조회 화면에서 지역 옵션을 선택하는 기능 추가
  src/main/vue/src/components/meeting/SelectBox.vue
  src/main/vue/src/components/meeting/option-control/OptionControl.vue
  src/main/vue/src/components/meeting/option-control/Region.vue
  src/main/vue/src/stores/meetingListStore.js
  src/main/vue/src/views/meeting/List.vue
Labels: bug, feat

#136 feat: 인증 router-guard
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/vue/src/api/auth.js
  src/main/vue/src/api/index.js
  src/main/vue/src/components/header/Header.vue
  src/main/vue/src/components/meeting/Participants.vue
  src/main/vue/src/router/index.js
  src/main/vue/src/stores/memberStore.js
  src/main/vue/src/views/LoginProc.vue
  src/main/vue/src/views/meeting/Login.vue
  src/main/webapp/image/meeting/balck.jpg
  src/main/webapp/image/meeting/ha.jpg
Labels: feat, fix, v2

#138 Feature : User profile modal, notification modal
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/controller/NotificationController.java
  src/main/java/com/zpop/web/dao/NotificationDao.java
  src/main/java/com/zpop/web/dto/ParticipantResponse.java
  src/main/java/com/zpop/web/dto/ProfileResponse.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/DefaultNotificationService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/java/com/zpop/web/service/NotificationService.java
  src/main/resources/mapper/NotificationDaoMapper.xml
  src/main/vue/src/api/index.js
  src/main/vue/src/api/member.js
  src/main/vue/src/api/notification.js
  src/main/vue/src/assets/css/component/header.css
  src/main/vue/src/components/header/NotificationModal.vue
  src/main/vue/src/components/meeting/Participants.vue
  src/main/vue/src/components/meeting/UserProfile.vue
Labels: feat

#137 feat: 로그인 리다이렉트, 로그인 모달 개선 구현
  src/main/vue/src/components/header/Header.vue
  src/main/vue/src/components/modal/LoginModal.vue
  src/main/vue/src/router/index.js
  src/main/vue/src/stores/loginModalStore.js
  src/main/vue/src/views/Layout.vue
Labels: feat, refactoring, v2

#139 Participation.vue 에서 오타로 생긴 버그 수정
  src/main/java/com/zpop/web/controller/NotificationController.java
  src/main/resources/static/css/member/component/notification-modal.css
  src/main/vue/src/components/header/NotificationModal.vue
  src/main/vue/src/components/meeting/Participants.vue
Labels: bug

#141 Feat: 검색 toggle
  src/main/vue/src/components/meeting/option-control/OptionControl.vue
  src/main/vue/src/views/meeting/Search.vue
Labels: feat, v2

#142 Fixed/mypage
  package-lock.json
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dto/MyMeetingResponse.java
  src/main/vue/src/api/member.js
  src/main/vue/src/components/member/MyProfile.vue
  src/main/vue/src/components/member/ProfileEdit.vue
  src/main/vue/src/views/member/Edit.vue
  src/main/vue/src/views/member/Profile.vue
Labels: fix

#144 Feature/comment
  src/main/java/com/zpop/web/controller/CommentController.java
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/ReplyController.java
  src/main/resources/application.properties
  src/main/vue/src/api/comment.js
  src/main/vue/src/api/index.js
  src/main/vue/src/assets/css/meeting/component/comment.css
  src/main/vue/src/assets/css/meeting/component/reply.css
  src/main/vue/src/assets/css/meeting/component/select.css
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/Reply.vue
  src/main/vue/src/components/comment/ReplyList.vue
  src/main/vue/src/components/meeting/Comments.vue
  src/main/vue/src/stores/commentStore.js
  src/main/vue/src/views/meeting/Detail.vue
Labels: feat

#145 feat: detail article btn
  src/main/java/com/zpop/web/dto/MeetingDetailResponse.java
  src/main/vue/src/assets/css/meeting/article.css
  src/main/vue/src/components/button/Round.vue
  src/main/vue/src/components/button/RoundDisabled.vue
  src/main/vue/src/components/meeting/Article.vue
  src/main/vue/src/views/meeting/Detail.vue
Labels: feat, refactoring, v2

#146 fix: comment input box not showing bug
  src/main/vue/src/components/comment/Comment.vue
Labels: fix

#147 fix: final fix for comment
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/Reply.vue
  src/main/vue/src/components/comment/ReplyList.vue
Labels: fix

#148 feat: 모임 참여
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/global/exception/ExceptionHandlerControllerAdvice.java
  src/main/java/com/zpop/web/global/exception/ExceptionHandlerRestControllerAdvice.java
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/meeting/Article.vue
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
  src/main/vue/src/components/modal/Default.vue
  src/main/vue/src/views/meeting/Detail.vue
Labels: feat, fix, refactoring, v2

#149 feat: 모임 참여 취소
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
Labels: feat, v2

#151 feat: 모임 마감하기 + 모임 상세 store
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/meeting/Participants.vue
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
  src/main/vue/src/stores/meetingDetailStore.js
  src/main/vue/src/views/meeting/Detail.vue
Labels: feat, refactoring, v2

#152 refactor: 모임 참여 취소
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
  src/main/vue/src/stores/meetingDetailStore.js
Labels: refactoring, v2

#153 feat: 모임 참여 후 모임 연락처 얻기
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/meeting/article/ControlModal.vue
Labels: feat, v2

#154 [FEAT] 관리자 페이지 추가 & 관리자 신고 기능 추가
  src/main/java/com/zpop/web/controller/admin/ReportController.java
  src/main/java/com/zpop/web/dao/CommentDao.java
  src/main/java/com/zpop/web/dao/MeetingDao.java
  src/main/java/com/zpop/web/dao/MemberDao.java
  src/main/java/com/zpop/web/dao/ReportedCommentDao.java
  src/main/java/com/zpop/web/dao/ReportedMeetingDao.java
  src/main/java/com/zpop/web/dao/ReportedMemberDao.java
  src/main/java/com/zpop/web/dto/admin/AdminReportedCommentDto.java
  src/main/java/com/zpop/web/dto/admin/AdminReportedMeetingDto.java
  src/main/java/com/zpop/web/dto/admin/AdminReportedMemberDto.java
  src/main/java/com/zpop/web/service/admin/AdminReportService.java
  src/main/java/com/zpop/web/service/admin/DefaultAdminReportService.java
  src/main/resources/mapper/CommentDaoMapper.xml
  src/main/resources/mapper/MeetingDaoMapper.xml
  src/main/resources/mapper/MemberDaoMapper.xml
  src/main/resources/mapper/ReportedCommentDaoMapper.xml
  src/main/resources/mapper/ReportedMeetingDaoMapper.xml
  src/main/resources/mapper/ReportedMemberDaoMapper.xml
  src/main/vue/src/api/admin/index.js
  src/main/vue/src/api/admin/meeting.js
  src/main/vue/src/assets/css/admin/component/admin-list.css
  src/main/vue/src/assets/css/admin/component/button.css
  src/main/vue/src/assets/css/admin/component/select.css
  src/main/vue/src/assets/css/admin/component/status.css
  src/main/vue/src/assets/css/admin/component/table-bar.css
  src/main/vue/src/assets/css/button.css
  src/main/vue/src/assets/css/deco.css
  src/main/vue/src/assets/css/icon.css
  src/main/vue/src/components/admin/Category.vue
  src/main/vue/src/components/admin/Header.vue
  src/main/vue/src/components/admin/SearchBar.vue
  src/main/vue/src/components/admin/Table.vue
  src/main/vue/src/components/admin/TableHeader.vue
  src/main/vue/src/components/admin/modal/AdminModal.vue
  src/main/vue/src/router/admin.js
  src/main/vue/src/views/admin/Home.vue
  src/main/vue/src/views/admin/Layout.vue
  src/main/vue/src/views/admin/report/Comment.vue
  src/main/vue/src/views/admin/report/Meeting.vue
  src/main/vue/src/views/admin/report/Member.vue
  src/main/vue/src/views/admin/report/Report.vue
Labels: feat, v2

#157 [FEAT] 관리자 사용자 관리 기능 추가 (조회만 가능)
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/ReportController.java
  src/main/java/com/zpop/web/controller/admin/MemberController.java
  src/main/java/com/zpop/web/dao/MemberEvalDao.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/admin/AdminMemberEvalDto.java
  src/main/java/com/zpop/web/dto/admin/AdminParticipationDto.java
  src/main/java/com/zpop/web/service/admin/AdminMemberService.java
  src/main/java/com/zpop/web/service/admin/DeafultAdminMemberService.java
  src/main/resources/mapper/MemberEvalDaoMapper.xml
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/vue/src/components/header/Header.vue
  src/main/vue/src/views/Layout.vue
  src/main/vue/src/views/admin/Hader.vue
  src/main/vue/src/views/admin/member/Evaluation.vue
  src/main/vue/src/views/admin/member/List.vue
  src/main/vue/src/views/admin/member/Member.vue
  src/main/vue/src/views/admin/member/Participation.vue
Labels: feat, help wanted, v2

#159 [FIX] 모임글 등록 시 입력값이 유효하지 않은 경우에도 정상 처리되는 모달로 전환되는 이슈 해결
  src/main/vue/src/utils/RegisterForm.js
  src/main/vue/src/views/meeting/Register.vue
Labels: fix

#160 [FIX] 메인 조회화면에서 지역옵션 선택 시 3개 이상 고르는 경우 무조건 마지막 지역이 없어지는 버그 수정
  src/main/vue/src/components/meeting/option-control/Region.vue
Labels: fix

#161 [FEAT, REFACTOR] 로그인 기능 개선 및 카카오 로그인 기능 수정
  src/main/vue/src/components/modal/LoginModal.vue
  src/main/vue/src/router/index.js
  src/main/vue/src/views/LoginProc.vue
  src/main/vue/src/views/meeting/List.vue
Labels: feat, refactoring

#162 [FEAT] 모임글 상세보기에서 사용되는 select modal 추가
  src/main/vue/src/assets/css/meeting/component/select.css
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/SelectModal.vue
Labels: feat

#163 fix: 모든 컴포넌트 views에서 scroll event 발생
  src/main/vue/src/views/meeting/List.vue
  src/main/vue/src/views/meeting/Search.vue
Labels: fix

#150 fix: 내 프로필 수정
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/MemberDao.java
  src/main/java/com/zpop/web/dao/NicknameLogDao.java
  src/main/java/com/zpop/web/entity/NicknameLog.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/mapper/MemberDaoMapper.xml
  src/main/resources/mapper/NicknameLogDaoMapper.xml
  src/main/vue/src/assets/css/admin/component/select.css
  src/main/vue/src/components/member/MeetingList.vue
  src/main/vue/src/components/member/ProfileEdit.vue
  src/main/vue/src/views/member/Edit.vue
  src/main/vue/src/views/member/MyMeeting.vue
Labels: feat, fix, v2

#169 feat: 어드민 로그인 및 백엔드 전역 예외관리
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/admin/AuthController.java
  src/main/java/com/zpop/web/dao/AdminDao.java
  src/main/java/com/zpop/web/dto/admin/auth/AdminLoginDto.java
  src/main/java/com/zpop/web/dto/admin/auth/AdminResponse.java
  src/main/java/com/zpop/web/entity/Admin.java
  src/main/java/com/zpop/web/global/exception/CustomException.java
  src/main/java/com/zpop/web/global/exception/ExceptionHandlerRestControllerAdvice.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/global/exception/ExceptionResponseBody.java
  src/main/java/com/zpop/web/security/SecurityConfig.java
  src/main/java/com/zpop/web/security/UserSecurityService.java
  src/main/java/com/zpop/web/security/ZpopUserDetails.java
  src/main/resources/mapper/AdminDaoMapper.xml
  src/main/vue/src/api/admin/auth.js
  src/main/vue/src/api/admin/index.js
  src/main/vue/src/router/admin.js
  src/main/vue/src/router/index.js
  src/main/vue/src/stores/memberStore.js
  src/main/vue/src/views/admin/Login.vue
Labels: feat, v2

#170 fix: Region css
  src/main/vue/src/components/meeting/option-control/Region.vue
Labels: fix

#171 feat: comment kebob delete
  src/main/vue/src/api/comment.js
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentModal.vue
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/components/meeting/article/Article.vue
Labels: feat

#172 refactor: 모임 참여하기
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dto/ParticipationResponse.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
Labels: refactoring, v2

#173 feat: 모임 조회 셀렉트 모달에 role 적용
  src/main/vue/src/components/meeting/article/Article.vue
Labels: feat, v2

#174 feat participationlist and UserProfile
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/resources/static/css/member/member/profile-modal.css
  src/main/vue/src/api/index.js
  src/main/vue/src/api/member.js
  src/main/vue/src/api/report.js
  src/main/vue/src/assets/css/meeting/component/report-modal.css
  src/main/vue/src/components/meeting/Participant.vue
  src/main/vue/src/components/meeting/ParticipantList.vue
  src/main/vue/src/components/meeting/UserProfile.vue
  src/main/vue/src/views/admin/meeting/List.vue
  src/main/vue/src/views/meeting/Detail.vue
Labels: feat

#178 fix: 알림 경로 수정
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/vue/src/components/header/Header.vue
  src/main/vue/src/components/header/NotificationModal.vue
Labels: feat, fix

#180 feat : report modal
  src/main/java/com/zpop/web/controller/ReportController.java
  src/main/vue/src/components/meeting/UserProfile.vue
  src/main/vue/src/components/member/ReportUser.vue
Labels: feat

#183 Feature/kebob - 삭제기능 완성
  src/main/java/com/zpop/web/utils/ElapsedTimeCalculator.java
  src/main/vue/src/api/comment.js
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/comment/CommentModal.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/ReplyList.vue
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/stores/commentStore.js
  src/main/vue/src/stores/meetingDetailStore.js
  src/main/vue/src/stores/replyStore.js
  src/main/vue/src/views/meeting/Detail.vue
Labels: feat

#182 feat: 모임 select modal 링크 복사, 모임 수정 & 403 & 모임 예외 핸들링
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/resources/static/images/lock.svg
  src/main/vue/src/components/meeting/article/SelectModal.vue
  src/main/vue/src/router/index.js
  src/main/vue/src/utils/UpdateForm.js
  src/main/vue/src/views/403.vue
  src/main/vue/src/views/meeting/Detail.vue
  src/main/vue/src/views/meeting/Update.vue
Labels: feat, refactoring, v2

#185 [fix] detail page css
  src/main/java/com/zpop/web/utils/ElapsedTimeCalculator.java
  src/main/vue/src/assets/css/meeting/component/comment.css
  src/main/vue/src/views/meeting/Detail.vue
Labels: fix

#186 feat: 모임 삭제하기
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
  src/main/vue/src/components/meeting/article/SelectModal.vue
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat, v2

#192 [FIX] 경미한 CSS 버그 수정
  src/main/vue/src/assets/css/meeting/article.css
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/option-control/Region.vue
Labels: fix

#190 [FEAT] CSS loader 추가
  src/main/vue/src/components/PageLoader.vue
  src/main/vue/src/utils/RegisterForm.js
  src/main/vue/src/views/meeting/List.vue
  src/main/vue/src/views/meeting/Register.vue
Labels: feat

#193 feat: 새로운 배너추가! & 프로필 수정 모달들 추가
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/ProfileFileDao.java
  src/main/java/com/zpop/web/entity/ProfileFile.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/mapper/ProfileFileDaoMapper.xml
  src/main/resources/static/css/member/component/notification-modal.css
  src/main/resources/static/images/banner-jpg1.jpg
  src/main/resources/static/images/banner-jpg2.jpg
  src/main/resources/static/images/banner-jpg3.jpg
  src/main/vue/src/assets/css/form.css
  src/main/vue/src/components/header/NotificationModal.vue
  src/main/vue/src/components/meeting/Banner.vue
  src/main/vue/src/components/member/MyProfile.vue
  src/main/vue/src/components/member/ProfileEdit.vue
  src/main/vue/src/components/modal/Changed.vue
  src/main/vue/src/views/member/Edit.vue
Labels: feat, help wanted, v2

#191 [FEAT] 메인화면에서 스크롤바 상단 이동 버튼 및 모임글 추가 버튼 추가
  src/main/resources/static/images/icon/button-plus.svg
  src/main/resources/static/images/icon/button-up.svg
  src/main/vue/src/assets/css/component/header.css
  src/main/vue/src/components/meeting/RegisterMeetingBtn.vue
  src/main/vue/src/components/meeting/ScrollUpBtn.vue
  src/main/vue/src/views/meeting/List.vue
Labels: feat

#188 refactor: 모임 참여자 컴포넌트
  src/main/vue/src/components/meeting/MemberProfile.vue
  src/main/vue/src/components/meeting/Participant.vue
  src/main/vue/src/components/meeting/ParticipantList.vue
  src/main/vue/src/components/meeting/UserProfile.vue
Labels: feat, refactoring, v2

#196 Feat : 모임 신고 모달과 기능 구현, 중복 신고 예외 처리
  src/main/java/com/zpop/web/controller/ReportController.java
  src/main/java/com/zpop/web/dto/RequestMeetingReportDto.java
  src/main/java/com/zpop/web/dto/RequestMemberReportDto.java
  src/main/resources/static/css/member/component/report-modal.css
  src/main/vue/src/api/report.js
  src/main/vue/src/assets/css/meeting/component/report-modal.css
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/SelectModal.vue
  src/main/vue/src/components/report/ReportCompleteModal.vue
  src/main/vue/src/components/report/ReportMeeting.vue
Labels: feat

#187 feat: copied tooltip
  src/main/resources/static/css/tooltip.css
  src/main/vue/src/assets/css/component/tooltip.css
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/SelectModal.vue
Labels: feat, v2

#199 Feature/kebob edit
  src/main/vue/src/assets/css/meeting/component/reply.css
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/comment/CommentModal.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/Reply.vue
  src/main/vue/src/components/comment/ReplyList.vue
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/stores/commentStore.js
  src/main/vue/src/stores/replyStore.js
Labels: refactoring

#198 feat: 모든 view 이동시 스크롤 상단 고정
  src/main/vue/src/router/index.js
Labels: feat, v2

#204 feat : notification 모달 버그 수정, 알림 순서 정렬
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/java/com/zpop/web/controller/NotificationController.java
  src/main/java/com/zpop/web/dao/NotificationDao.java
  src/main/java/com/zpop/web/service/DefaultCommentService.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/resources/mapper/NotificationDaoMapper.xml
  src/main/vue/src/api/notification.js
  src/main/vue/src/components/header/NotificationModal.vue
Labels: feat, fix

#202 feat: 모임 참여 링크 얻기
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/controller/TempMeetingController.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/article/ControlModal.vue
  src/main/vue/src/components/meeting/article/SelectModal.vue
Labels: feat, refactoring

#206 refactor: 회원 프로필 조회
  src/main/java/com/zpop/web/controller/LoginController.java
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/dao/ParticipationDao.java
  src/main/java/com/zpop/web/dto/ProfileResponse.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/service/DefalutMemberService.java
  src/main/java/com/zpop/web/service/MemberService.java
  src/main/resources/mapper/ParticipationDaoMapper.xml
  src/main/vue/src/components/meeting/MemberProfile.vue
Labels: feat, refactoring

#207 [Fix] hot fix for report select modal
  src/main/vue/src/components/comment/SelectModal.vue
Labels: fix

#208 feat : 댓글 신고 기능 구현
  src/main/java/com/zpop/web/controller/ReportController.java
  src/main/vue/src/api/report.js
  src/main/vue/src/assets/css/meeting/component/report-modal.css
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/components/report/ReportComment.vue
Labels: feat

#209 feat: 참여자 프로필 조회시 "내보내기" "신고하기" 렌더링 여부
  src/main/vue/src/components/meeting/MemberProfile.vue
Labels: feat, v2

#210 feat: 참여자 프로필 조회시 탈퇴 여부
  src/main/resources/static/images/no-rusult-ghost.svg
  src/main/vue/src/components/meeting/MemberProfile.vue
  src/main/vue/src/components/meeting/article/Article.vue
Labels: feat

#212 Feature/ 댓글시간에 (수정됨) 추가
  src/main/java/com/zpop/web/dto/CommentResponse.java
  src/main/java/com/zpop/web/entity/comment/CommentView.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/vue/src/api/comment.js
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/Reply.vue
  src/main/vue/src/components/comment/ReplyList.vue
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/stores/commentStore.js
Labels: refactoring

#216 [FEAT] comment & reply kebob select menu 완료
  src/main/vue/src/api/comment.js
  src/main/vue/src/components/comment/Comment.vue
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/comment/CommentModal.vue
  src/main/vue/src/components/comment/InputBox.vue
  src/main/vue/src/components/comment/Reply.vue
  src/main/vue/src/components/comment/ReplyList.vue
  src/main/vue/src/components/comment/SelectModal.vue
Labels: feat

#213 Feat : 로그인한 사용자만 댓글과 모임 신고 가능
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/report/ReportMeeting.vue
Labels: feat

#215 feat: 디테일, 메인, 버튼, 마이프로필 css 개선 및 동적 클래스 변경
  src/main/java/com/zpop/web/controller/MemberController.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/resources/static/css/icon.css
  src/main/resources/static/images/icon/calendar20.svg
  src/main/resources/static/images/icon/location-20.svg
  src/main/vue/src/assets/css/component/header.css
  src/main/vue/src/assets/css/icon.css
  src/main/vue/src/assets/css/meeting/article.css
  src/main/vue/src/assets/css/meeting/thumbnail-list.css
  src/main/vue/src/assets/css/member/mypage.css
  src/main/vue/src/components/comment/CommentList.vue
  src/main/vue/src/components/meeting/article/Article.vue
  src/main/vue/src/components/meeting/option-control/OptionControl.vue
  src/main/vue/src/components/member/MeetingList.vue
  src/main/vue/src/components/member/ProfileEdit.vue
  src/main/vue/src/views/member/MyGathering.vue
  src/main/vue/src/views/member/MyMeeting.vue
  src/main/webapp/image/meeting/balck.jpg
  src/main/webapp/image/meeting/ha.jpg
  src/main/webapp/image/meeting/java.png
  src/main/webapp/image/meeting/다운로드 (1).jpg
Labels: cleanup, feat, fix, v2

#223 fix: 모임 등록 view 버튼 css
  src/main/vue/src/views/404.vue
  src/main/vue/src/views/meeting/Register.vue
Labels: fix, v2

#225 feat : 사용자 신고 구현 및 css 수정
  src/main/vue/src/assets/css/meeting/component/report-modal.css
  src/main/vue/src/components/comment/SelectModal.vue
  src/main/vue/src/components/meeting/MemberProfile.vue
  src/main/vue/src/components/meeting/ParticipantList.vue
  src/main/vue/src/components/report/ReportUser.vue
Labels: feat

#227 [Cleanup] import에서 defineProps와 defineEmits제거 -2차분-
  src/main/vue/index.html
  src/main/vue/src/components/PageLoader.vue
  src/main/vue/src/components/admin/modal/AdminDetailModal.vue
  src/main/vue/src/components/admin/modal/AdminModal.vue
  src/main/vue/src/components/button/SoftToggle.vue
  src/main/vue/src/components/comment/ReplyList.vue
  src/main/vue/src/components/header/NotificationModal.vue
  src/main/vue/src/components/meeting/Participant.vue
  src/main/vue/src/components/meeting/option-control/SearchBar.vue
  src/main/vue/src/components/modal/Changed.vue
  src/main/vue/src/components/modal/Default.vue
  src/main/vue/src/components/modal/Full.vue
  src/main/vue/src/components/modal/ServerError.vue
  src/main/vue/src/components/report/ReportCompleteModal.vue
Labels: cleanup

#228 feat: /404
  src/main/java/com/zpop/web/controller/CustomErrorController.java
  src/main/vue/vite.config.js
  src/main/webapp/image/meeting/c.png
  src/main/webapp/image/meeting/potato.jpg
Labels: feat

#231 feat: 모임 내보내기 백엔드
  src/main/java/com/zpop/web/controller/MeetingController.java
  src/main/java/com/zpop/web/dto/KickDto.java
  src/main/java/com/zpop/web/global/exception/ExceptionReason.java
  src/main/java/com/zpop/web/service/DefaultMeetingService.java
  src/main/java/com/zpop/web/service/MeetingService.java
  src/test/java/com/zpop/web/service/DefaultMeetingServiceTest.java
Labels: feat

#233 feat: 내가 참여한 모임의 모달창 애니메이션 적용, 평가하기 버그 수정, 모임등록 css 개선
  README.md
  src/main/java/com/zpop/web/controller/HomeController.java
  src/main/vue/src/assets/css/component/select.css
  src/main/vue/src/assets/css/form.css
  src/main/vue/src/components/member/MeetingList.vue
  src/main/vue/src/components/member/MyMeeting.vue
  src/main/vue/src/components/modal/Changed.vue
  src/main/vue/src/components/modal/Full.vue
Labels: feat, fix, v2

#236 fix: 신고 모달 바디 색상 css 수정
  src/main/vue/src/assets/css/meeting/component/report-modal.css
Labels: feat

#235 style: 모임 썸네일 hover & active css
  src/main/vue/src/components/meeting/Thumbnail.vue
Labels: v2

#237 feat: 내보내기 vue 구현
  src/main/vue/src/api/meeting.js
  src/main/vue/src/components/participant/MemberProfile.vue
  src/main/vue/src/components/participant/ParticipantList.vue
Labels: feat

#238 feat: 모임 평가후 컴포넌트 동적으로 변경
  src/main/vue/src/views/member/MyMeeting.vue
Labels: v2

#240 fix: 평가하기 클릭시, 무조건 참여자 없는 에러 뜨던 현상 수정
  src/main/vue/src/views/member/MyMeeting.vue
Labels: fix, v2
